-- Copyright (c) 2019 Trevor Redfern
--
-- This software is released under the MIT License.
-- https://opensource.org/licenses/MIT

local male = {
  "Abanu", "Abe", "Abel", "Abram", "Abramnam", "Adain", "Adair", "Adam", "Adan", "Adar", "Adommus", "Adon", "Adrian",
  "Adzin", "Aerwyck", "Afarmis", "Agater", "Agus", "Aiden", "Aiken", "Airden", "Airen", "Ajani", "Akre", "Aladian",
  "Alakin", "Albers", "Albert", "Albert", "Aldir", "Aldor", "Aldor", "Aldrick", "Aldwen", "Alfie", "Alfie", "Alfonz",
  "Alfred", "Alian", "Alin", "Alix", "Allen", "Alvers", "Alvert", "Amal", "Amari", "Ander", "Anders", "Andor",
  "Andrema", "Andrew", "Angus", "Anson", "Anton", "Antonio", "Antony", "Anzil", "Anzonio", "Anzony", "Apfel",
  "Aratham", "Arcus", "Arel", "Arfel", "Argus", "Arinn", "Arman", "Aroll", "Arrux", "Artie", "Artimus", "Arturo",
  "Arujo", "Arykk", "Asfar", "Asten", "Aster", "Atom", "Audrey", "Austen", "Auzten", "Avery", "Avis", "Avril",
  "Axalnor", "Axel", "Axel", "Axelrod", "Axil", "Axley", "Axly", "Axyl", "Azam", "Azam", "Azar", "Azimir", "Aziz",
  "Azizi", "Azud",
  "Badin", "Badrick", "Badryk", "Baird", "Baker", "Balatiq", "Baldar", "Baldemar", "Balder", "Baldmar", "Baldric",
  "Baldrick", "Baldwin", "Balmar", "Bancroft", "Barach", "Baradin", "Baradine", "Baradon", "Barclay", "Bard",
  "Barden", "Bardick", "Bardil", "Bardon", "Bardur", "Bardyn", "Barin", "Barnabus", "Barnaby", "Barnett", "Barney",
  "Baron", "Barradin", "Barredith", "Barric", "Barris", "Barron", "Bart", "Barth", "Barthel", "Bartholomew",
  "Bartholomus", "Bartimus", "Baskon", "Basu", "Basyr", "Battista", "Baxter", "Bays", "Beacher", "Bear",
  "Beckhamm", "Beecher", "Beldon", "Beloc", "Belos", "Ben", "Benjamin", "Benjin", "Benson", "Bentlye", "Beresford",
  "Bergivin", "Berkleah", "Bern", "Bernie", "Berringar", "Bertran", "Bertrand", "Besos", "Bevin", "Bezos",
  "Biff", "Biflen", "Bill", "Billand", "Billu", "Binkendar", "Binkentios", "Birgendo", "Bishop",
  "Bislen", "Bistar", "Blade", "Blake", "Blayne", "Bledri", "Bodin", "Bok", "Boradin", "Bormeros", "Bosmir",
  "Bradlun", "Brahm", "Bran", "Brand", "Brandle", "Brandon", "Branlin", "Brax", "Brent", "Brock",
  "Brodin", "Bruno", "Burk", "Burke", "Burl", "Burnabus", "Burnaby", "Burr", "Burril", "Burt", "Buster", "Butch",
  "Byrian", "Byron", "Bysh",
  "Caalas", "Caallaham", "Caard", "Caarl", "Cabe", "Cadall", "Cadbey", "Caddak", "Caddock", "Cadmar", "Cadwallen",
  "Caedfer", "Cael", "Caffin", "Cafill", "Cahil", "Cahill", "Cai", "Caius", "Caizlo", "Calahan", "Calbert", "Calder",
  "Caldwell", "Cale", "Caleb", "Calhelm", "Calhoun", "Calistoph", "Calix", "Calix", "Callum", "Calven", "Cameron",
  "Cameros", "Camidor", "Cane", "Cappa", "Cardul", "Carlisle", "Carlos", "Carlton", "Carmine", "Carrick",
  "Carrik", "Carswell", "Carter", "Cartez", "Cartright", "Carvel", "Casey", "Cash", "Casius", "Caslav", "Casper",
  "Cassem", "Cassien", "Cathmor", "Cavan", "Cawley", "Cayro", "Cecil", "Cedro", "Cesar", "Chad", "Chadwick",
  "Chago", "Chalos", "Chanan", "Chance", "Chancy", "Chandler", "Chandon", "Charampios", "Charles", "Charwyk",
  "Chase", "Chaucer", "Cheng", "Chester", "Christo", "Christof", "Churrin", "Clancy", "Clavers", "Clay",
  "Clete", "Cliff", "Clint", "Clive", "Cob", "Coburn", "Coby", "Coen", "Colim", "Colimir", "Colin", "Collum",
  "Corbanos", "Corben", "Cordan", "Cornelius", "Corwyn", "Costello", "Crawley", "Crispen", "Crispin", "Cristallven",
  "Curris", "Currit", "Curtis",
  "Dabar", "Daegon", "Daegyn", "Daenell", "Dak", "Dal", "Dalaney", "Dale", "Dale", "Dalman", "Dalton", "Damario",
  "Damien", "Damion", "Dammos", "Damon", "Dana", "Danden", "D'Andre", "Danforth", "Danielson", "Daniul", "Daniz",
  "Danniel", "Dannis", "Dannyl", "Dansil", "Darbee", "Dard", "Darence", "Darg", "Daril", "Darin", "Dario", "Darius",
  "Darkon", "Darnel", "Darren", "Darrin", "Darryl", "Darvel", "Darvenun", "Daryl", "Davee", "Daven", "David",
  "Davis", "Davit", "Davos", "Dav'rin", "Dawsin", "Dawson", "Dax", "Dax", "Daye", "Dayle", "Dayv", "Dearbon",
  "Deavon", "Dech", "Decimus", "Deen", "Deevan", "Deffin", "Deffir", "Dekel", "Dekyln", "Delhelm", "Dellmir",
  "Demetir", "Dempsey", "Denison", "Denmen", "Denton", "Denu", "Derik", "Dermott", "Deros", "Derrak", "Derrik",
  "Devon", "Devor", "Dewan", "Dex", "Dexter", "Deymour", "Diaz", "Dickon", "Dikon", "Diondar", "Dirk", "Dirken",
  "Donahu", "Donatyen", "Donavan", "Dorrit", "Doug", "Douglaas", "Douglas", "Dover", "Doverin", "Dragyn", "Draj",
  "Drake", "Draper", "Draper", "Droggo", "Drummund", "Dryden", "Dugger", "Duglan", "Durant", "Duree", "Durwood",
  "Dusteen", "Dutch", "Duysell",
  "Eadenz", "Eamon", "Earl", "Earl", "Earland", "Earvin", "Earzem", "Eastibil", "Easton", "Eaton", "Eben", "Eberhard",
  "Ebert", "Ebo", "Eccelinno", "Edderick", "Eddie", "Eddrick", "Ede", "Edgar", "Edge", "Edgen", "Edii",
  "Edmon", "Edmund", "Edom", "Edryck", "Edsellon", "Edson", "Edwaldo", "Efrani", "Egbert", "Egen", "Egmount",
  "Eilief", "Einfeld", "Eirian", "Eiton", "Elam", "Elan", "Elben", "Eldun", "Eleck", "Elek", "Elezar", "Elgan",
  "Eli", "Eliann", "Elias", "Eliaz", "Eliot", "Elizardin", "Elke", "Elkyn", "Ellis", "Ellis", "Elliz", "Elmarr",
  "Elon", "Elrad", "Elroy", "Elton", "Elvin", "Elvindar", "Elwood", "Elwynn", "Elzon", "Emad", "Emerson", "Emile",
  "Emilio", "Emmerick", "Emmett", "Emmit", "Enapai", "Enderez", "Endrykas", "Enestor", "Engleburt", "Enric", "Enright",
  "Enzo", "Eoin", "Erek", "Erik", "Ermand", "Ernest", "Ernie", "Ernie", "Ernil", "Errell", "Erret", "Erroll",
  "Erstwick", "Ervem", "Ervin", "Esaw", "Esburne", "Eskil", "Eskyl", "Etien", "Eugene", "Evan", "Evengy", "Evondan",
  "Ewald", "Ewan", "Ewold", "Eyddwyn", "Ezikiel", "Ezra", "Ezren",
  "Fabrizo", "Fabyn", "Fadlin", "Fairfax", "Faizal", "Falamin", "Falamir", "Falco", "Faleros", "Falkbert", "Falkner",
  "Falkoz", "Fallor", "Falmor", "Farakor", "Farmir", "Farralir", "Farrand", "Farrell", "Farrook", "Farrow", "Fatinar",
  "Fausto", "Fayette", "Fedorza", "Feek", "Felip", "Felix", "Felton", "Feodor", "Ferdinan", "Ferdinand", "Fergus",
  "Fergus", "Ferko", "Ferrars", "Ferrys", "Feryn", "Festus", "Fiir", "Filbert", "Fin", "Findley", "Fineas", "Finelion",
  "Finian", "Finnegan", "Finnezar", "Fiorezzo", "Firth", "Firus", "Fitzgerard", "Fitzhugh", "Fitzroy", "Fitzwald",
  "Flanders", "Flash", "Flazius", "Flemming", "Fletcher", "Flimore", "Flinn", "Flint", "Flitwick", "Flix", "Florio",
  "Floyd", "Floyfre", "Foluke", "Fontaine", "Fonz", "Forbes", "Ford", "Fordyn", "Forest", "Fortanan",
  "Frank", "Frank", "Franklin", "Franko", "Franz", "Franzen", "Fray", "Frazien", "Frazier", "Fredderis", "Freddi",
  "Freddie", "Freddizzo", "Frederick", "Frederick", "Freidan", "Fremont", "Frewin", "Frick", "Fridmar", "Fridmund",
  "Fridoff", "Frigmund", "Frowin", "Fulleman", "Fuller", "Fullerton", "Fulton", "Fuzen", "Fydore", "Fyllyk",
  "Fynion", "Fynyn",
  "Gabe", "Gabriel", "Gael", "Gage", "Gailtos", "Gaius", "Galbraith", "Galilino", "Galin", "Gallagher", "Galloway",
  "Gallum", "Galt", "Galton", "Galvay", "Galven", "Galvin", "Galwynn", "Galzpar", "Gamal", "Gamble", "Gambyl",
  "Gamerin", "Gamlin", "Gannon", "Gard", "Gardnar", "Garenth", "Gareth", "Garian", "Garion", "Garnier", "Garok",
  "Garrard", "Garrek", "Garrent", "Garrin", "Garryck", "Garryt", "Garth", "Garton", "Garund", "Garvax", "Garve",
  "Garver", "Garvin", "Garviz", "Garvus", "Garwin", "Garwood", "Garyk", "Garyth", "Gaspent", "Gasper", "Gasper",
  "Gaston", "Gavin", "Gavinryn", "Gavril", "Gavril", "Gawain", "Gax", "Gaydin", "Gaylor", "Gaynor", "Gazar",
  "Gazo", "Gazparzen", "Geary", "Gemalli", "Genaro", "Gene", "Gent", "Geoff", "George", "Gervais", "Gerwyne",
  "Gesar", "Gesham", "Gibor", "Gilad", "Gilbert", "Gilders", "Giles", "Gill", "Gillet", "Gillwen", "Gilmore",
  "Gilroy", "Gladwin", "Glazer", "Godfrey", "Goldwin", "Gordon", "Gordon", "Gorgol", "Gorman", "Gorus", "Gothax",
  "Gothmar", "Gothna", "Grandon", "Grant", "Gravin", "Graydon", "Gregor", "Gregus", "Greig", "Griffin", "Griffith",
  "Guestus", "Guntar", "Guntero", "Guryon", "Gustav", "Gustonio", "Guy", "Gwern",
  "Haakon", "Hacim", "Hackytt", "Haddi", "Hadeon", "Hadrien", "Hadwinn", "Hageb", "Hagen", "Haidar", "Hailwell",
  "Haji", "Hakin", "Hakin", "Hako", "Hal", "Halbert", "Halburt", "Halcyon", "Haldan", "Hall", "Halleigh", "Hallon",
  "Hallvard", "Hallward", "Halmut", "Halonar", "Halsey", "Halstead", "Halston", "Halvers", "Halvor", "Hamed",
  "Hamelton", "Hamidy", "Hamill", "Hamlet", "Hamlyn", "Hammar", "Hammet", "Hammett", "Hammish", "Hammond", "Hamnet",
  "Hampson", "Handel", "Handley", "Hanford", "Hank", "Hank", "Hank", "Hannizal", "Hansel", "Hanus", "Harden",
  "Harding", "Hardon", "Hardun", "Hardun", "Hardwyn", "Haresh", "Hargreve", "Hargrove", "Hariell", "Harkin",
  "Harkyn", "Harlow", "Harman", "Harmenus", "Harmin", "Harold", "Harper", "Harpex", "Harree", "Harrington", "Harrison",
  "Harriz", "Harrod", "Harry", "Hart", "Hartvig", "Harwynn", "Haskell", "Haslett", "Hastings", "Havelock", "Havelocke",
  "Havigin", "Hawk", "Hawkeye", "Hawley", "Hayes", "Haynes", "Haywood", "Hazani", "Hazel", "Heath", "Heaton",
  "Hectir", "Hector", "Hedley", "Heilo", "Heinwick", "Helmut", "Henley", "Henru", "Henryck", "Henz", "Herbert",
  "Hercule", "Herman", "Herod", "Hersh", "Hibos", "Hildebrand", "Hildrichos", "Hilix", "Hilton", "Himesh", "Holbart",
  "Holmes", "Horatio", "Horus", "Howe", "Howie", "Hoyle", "Hradek", "Hugo", "Hugo", "Hume", "Humphrey", "Hunt",
  "Hunter", "Hunter", "Hux", "Huzzo", "Hywell",
  "Iago", "Iain", "Iainan", "Iakona", "Iakoza", "Ian", "Iantos", "Iantus", "Iben", "Ibrimir", "Ibsen", "Idderick",
  "Iddrick", "Ide", "Idmon", "Idris", "Idryss", "Ieke", "Iestir", "Ifans", "Ifor", "Iforzo", "Igal", "Iggy",
  "Ignacius", "Ignaz", "Igor", "Ilerios", "Ileros", "Illan", "Illard", "Illix", "Iltamus", "Iman", "Imaro",
  "Imbert", "Inar", "Indraz", "Ingmar", "Ingram", "Iniko", "Inir", "Ioan", "Ioman", "Iomar", "Iomer", "Ivaan",
  "Ivannir",
  "Jad", "Jadon", "Jak", "Jakkon", "Jallen", "Jallup", "Jamie", "Jamie", "Janzen", "Jase", "Jasek", "Jasken",
  "Jasper", "Jasper", "Jassik", "Jazar", "Jazon", "Jeffers", "Jeffersan", "Jeffrey", "Jeggus", "Jeldern", "Jenner",
  "Jennig", "Jenning", "Jennings", "Jeric", "Jerrik", "Jerrit", "Jerry", "Jessert", "Jessyrt", "Jon", "Jon",
  "Jonas", "Jonathon", "Jordan", "Jugo",
  "Kade", "Kadryn", "Kael", "Kahill", "Kahyr", "Kai", "Kai", "Kaislav", "Kaldwell", "Kalhoum", "Kartland",
  "Karvek", "Karver", "Kason", "Katal", "Kato", "Kavar", "Kay", "Kayleb", "Kee", "Keenam", "Keenan", "Kejl", "Kendall",
  "Kendar", "Kennlith", "Kennyth", "Kensie", "Kern", "Kerr", "Kessert", "Kevin", "Kevin", "Key", "Keyth", "Khaim",
  "Kiirk", "Kir", "Kiran", "Kiren", "Kistro", "Koran", "Kornyth", "Kovar", "Kovax", "Krandor", "Kyle",
  "Labury", "Lander", "Landers", "Lane", "Larry", "Larus", "Laurance", "Lawry", "Lax", "Laxton", "Layton", "Lazar",
  "Lazerus", "Leem", "Lesig", "Lesmas", "Lester", "Levrin", "Lex", "Lexor", "Leztor", "Liam", "Lindon", "Lionel",
  "Lionel", "Lionus", "Listen", "Lloyd", "Logan", "London", "Lorn", "Lorne", "Lorris",
  "Maaf", "Maal", "Mac", "Maddox", "Maddoz", "Madds", "Mads", "Maldern", "Malk", "Malken", "Malkin", "Maltazar",
  "Maltizar", "Malvin", "Manus", "Markus", "Martiin", "Marvin", "Marzino", "Mason", "Mason", "Mastalin", "Mateo",
  "Mathaseus", "Mathazi", "Mathius", "Matizar", "Matt", "Matthesius", "Max", "Maxfield", "Maz", "Maza", "Mazan",
  "Mazan", "Mazdar", "Mazerin", "Mazin", "Melcor", "Meldern", "Meldorn", "Melvin", "Merl", "Merlino", "Mertok",
  "Mervin", "Mezani", "Mezon", "Milo", "Mirvir", "Moldor", "Morton", "Motzar",
  "Nabor", "Nalo", "Naniel", "Nate", "Nate", "Nathan", "Nathanial", "Nathaniar", "Naviir", "Naviit", "Navin",
  "Navrisan", "Navryn", "Nay", "Nazanial", "Nazon", "Neemo", "Nel", "Neldern", "Nelin", "Nelvin", "Nestor", "Nethan",
  "Nevin", "Nibin", "Ni'ito", "Nillmet", "Nimban", "Nimon", "Nino", "Ninwe", "Nirrit", "Norbin", "Normantus", "Norton",
  "Nox",
  "Oberon", "Odin", "Oferion", "Oliver", "Olwen", "Orian", "Orin", "Orion", "Orion", "Oris", "Ortego", "Ortegus",
  "Orthus", "Oscar", "Oskan", "Oskar", "Osklin", "Othelian", "Othello", "Otis", "Owen", "Owen", "Oz", "Ozello",
  "Ozius", "Ozius", "Ozzie",
  "Pace", "Palan", "Paleros", "Paolo", "Paralan", "Paramir", "Pariim", "Paris", "Parker", "Pase", "Passlan",
  "Patrick", "Pax", "Payton", "Pellos", "Pender", "Percifen", "Percy", "Perox", "Perry", "Perzival", "Peter",
  "Petriche", "Pieter", "Pilarn", "Pilson", "Plavir", "Plax", "Pleem", "Prater", "Pratt", "Prentice", "Pruvis",
  "Quellin", "Quellos", "Quentin", "Quenton", "Quim", "Quinn", "Quint", "Quintul", "Quintus", "Quirl", "Quispen",
  "Quistar", "Quistevan", "Quiven", "Quizzel",
  "Raavim", "Radoz", "Radson", "Raihan", "Ramon", "Rask", "Raskon", "Rathius", "Ratoy", "Raz", "Rebault", "Reese",
  "Regenauld", "Reggie", "Reggie", "Reginald", "Restavan", "Reuben", "Revers", "Rex", "Rian", "Rian", "Riker", "Riley",
  "Riven", "River", "Rivon", "Rizandir", "Rizken", "Rob", "Robart", "Robert", "Roberto", "Robin", "Robitt",
  "Robyn", "Rogan", "Rogers", "Ronnie", "Rostaros", "Rozat", "Runin", "Rupert", "Ryland",
  "Salamir", "Salmis", "Salvin", "Sam", "Samin", "Sandris", "Sanford", "Santos", "Selden", "Seldon", "Serge",
  "Sergus", "Sevem", "Seven", "Shaevon", "Sheldon", "Shelton", "Shep", "Simon", "Simor", "Skaffrey", "Skip", "Skipic",
  "Spence", "Spence", "Spencer", "Spender", "Spenser", "Spike", "Spinault", "Stamner", "Stan", "Stanford", "Stanis",
  "Stanley", "Stanley", "Stann", "Stepjic", "Stevaniar", "Stowe", "Svenen", "Svenn", "Svenndar",
  "Talisen", "Taliver", "Tam", "Tambor", "Tamers", "Tamnor", "Tanat", "Tandor", "Tandris", "Tarvin", "Tavrin",
  "Tedd", "Tellander", "Tellmund", "Terrel", "Terrington", "Terry", "Terryon", "Thorne", "Tibbault", "Tim", "Timmoty",
  "Timon", "Timothy", "Tir", "Tirven", "Tmin", "Tmir", "Tmon", "Tod", "Tomas", "Tordis", "Torvul", "Trandis",
  "Trandor", "Trask", "Travindus", "Travis", "Traviz", "Trax", "Traxl", "Traxton", "Traymin", "Trevario", "Trevor",
  "Trey", "Treyvan", "Treyvon", "Ture", "Ty", "Tymr", "Tymyr",
  "Uagon", "Ullman", "Uman", "Unat", "Urden", "Urex", "Url", "Urvell", "Urven", "Ustanov", "Uston", "Utanion",
  "Utarios", "Uzrun",
  "Vade", "Valtor", "Van", "Vance", "Vandar", "Vander", "Vantos", "Vax", "Velenos", "Veppers", "Vesley", "Vexley",
  "Viktor", "Villem", "Villhelm", "Vin", "Viran", "Visnos",
  "Wade", "Wailyn", "Wallace", "Walli", "Walter", "Waltor", "Waltorn", "Ward", "Warren", "Warzell", "Wellben",
  "Weller", "Wellmen", "Wendell", "Wesley", "Wilgem", "Wilhelm", "Willamet", "Willem", "William", "Willis", "Wills",
  "Wilson", "Wilton", "Wolf", "Wolfgang",
  "Xain", "Xaltor", "Xander", "Xavier", "Xayd", "Xellin", "Xennin",
  "Yale", "Yarrow", "Yarsit", "Yedd", "Yelabin", "Yelavin", "Yellin", "Yen", "Yon",
  "Zaber", "Zadley", "Zago", "Zain", "Zalamir", "Zalastrin", "Zamerin", "Zami", "Zamie", "Zammeriin", "Zanaran",
  "Zandae", "Zander", "Zann", "Zantos", "Zantus", "Zarles", "Zatavin", "Zataz", "Zavier", "Zax", "Zayd", "Zayn",
  "Zed", "Zedden", "Zeddus", "Zeemus", "Zekk", "Zelander", "Zeldon", "Zellen", "Zellin", "Zen", "Zerl", "Zerrik",
  "Zodd", "Zranley", "Zulen",
}

local female = {
  "Abby", "Adina", "Aisha", "Akiko", "Alaine", "Alana", "Alenoko", "Alexa", "Alexandra", "Alexia", "Alhora", "Ali",
  "Alixa", "Alixandre", "Alixia", "Alora", "Alva", "Alvamira", "Ameiko", "Amiko", "Annalise", "Anne", "Anya",
  "Aowfar", "Aowyn", "Aoyll", "April", "Aramint", "Araminta", "Aresia", "Aria", "Armennia", "Aroush", "Artenia",
  "Arya", "Aster", "Astoria", "Augusta", "Ava", "Avenia", "Averil", "Averil", "Averinne", "Avery", "Avril", "Axaliz",
  "Ayala", "Azalea", "Azibell", "Azolynn",
  "Barbara", "Barzara", "Becka", "Belinadre", "Belinda", "Belinda", "Beliza", "Bella", "Belle", "Belle", "Bellina",
  "Berret", "Berryl", "Betaria", "Bethesda", "Bezani", "Bezanney", "Bolzari", "Braxia", "Bremiko", "Bressa", "Brezia",
  "Britt", "Brittani",
  "Cait", "Caitlyn", "Camilla", "Cammina", "Camora", "Candora", "Carinna", "Carlotta", "Carmen", "Casie", "Cassandra",
  "Cassie", "Cata", "Cathryn", "Catlyn", "Catlyn", "Catrina", "Catriona", "Caycee", "Caylee", "Cebelle", "Celeste",
  "Celestia", "Celinne", "Charlina", "Charlize", "Charlotte", "Chloe", "Ciel", "Cienna", "Cike", "Cindell",
  "Cirka", "Cora", "Corina", "Cressida",
  "Dahlia", "Dani", "Daniah", "Daniella", "Danika", "Daralyn", "Darcy", "Daria", "Darja", "Darota", "Dazeen",
  "Deanna", "Debborah", "Deena", "Deera", "Deevia", "Degede", "Della", "Dema", "Denise", "Deryn",
  "Des", "Devy", "Dextra", "Diama", "Diana", "Dianne", "Diazra", "Dionara", "Dira",
  "Doona", "Dora", "Doranna", "Doree", "Doreen", "Doreenia", "Dori", "Dorna", "Dorra", "Dorreen", "Dorvee", "Dozeria",
  "Dozzy", "Dressna",
  "Eanna", "Efania", "Effie", "Efonia", "Eframana", "Ejede", "Elaina", "Elana", "Elannah", "Elisa", "Elisandre",
  "Eliza", "Elizbet", "Ella", "Ellen", "Ellena", "Ellie", "Ellis", "Elouise", "Elsbara", "Elsbeth", "Ema",
  "Emeeka", "Emeera", "Emeerika", "Emesda", "Emiko", "Emleth", "Emma", "Emmy", "Eneka", "Epreh", "Eraka", "Eriko",
  "Erleth", "Erlyth", "Erma", "Ernesta", "Esandra", "Eugenia", "Eva", "Evalla", "Eveena", "Evella", "Evie",
  "Evira", "Evy", "Ezaldra", "Ezelia",
  "Fanny", "Feelia", "Felinare", "Fella", "Fenevere", "Fenna", "Fenrah", "Ferdia", "Ferdio", "Ferla", "Feya",
  "Fia", "Fienna", "Fiona", "Fionara", "Firi", "Florencia", "Florent", "Forlani", "Forlania", "Frances", "Francine",
  "Frankie", "Fredericka", "Fredia", "Fredricka", "Freyna", "Fricka",
  "Gabo", "Galeeza", "Galina", "Gawlenda", "Geena", "Gelina", "Geliosa", "Gelioza", "Gella", "Geneviere", "Genevieve",
  "Gerta", "Gesta", "Gia", "Gigi", "Gina", "Ginger", "Gisele", "Glenna", "Glinda", "Godrun", "Gorlanna", "Gorra",
  "Gracie", "Gracine", "Grepilzna", "Greta", "Gwen", "Gwendolyn", "Gwenevere", "Gwenyth",
  "Haely", "Hagrina", "Hailee", "Halaria", "Halena", "Hanna", "Hannah", "Hanzara", "Hazzin", "Hela", "Helen",
  "Helena", "Helleen", "Hester", "Higga", "Holli", "Holly", "Hora", "Horda", "Horta", "Hortance", "Hortence", "Horza",
  "Huma", "Hurla",
  "Iara", "Iendra", "Ienta", "Igrid", "Igrinna", "Illandri", "Illandria", "I'llania", "Illia", "Illith", "Ina",
  "Indarra", "Indira", "Indorra", "Indra", "Indriel", "Indya", "Inis", "Inzel", "Inziel", "Isa", "Isabeau", "Isabelle",
  "Isbeth", "Isla", "Izabel",
  "Jaleen", "Jalla", "Jamie", "J'arda", "Jarra", "Jasmina", "Jayne", "Jeen", "Jeffara", "Jella", "Jendana", "Jerila",
  "Jerilyn", "Jesska", "Jesta", "Jewel", "Jeyme", "Jezzika", "Jia", "Jocasta", "Joleen", "Jolie", "Jori",
  "Jori", "Julia", "Juliet", "Julietta", "Jusian", "Jynee", "Jynne",
  "Kailyn", "Kari", "Karima", "Karina", "Kasha", "Kassie", "Kata", "Kathryn", "Katia", "Katrijn", "Katya", "Kecia",
  "Keema", "Keesa", "Keila", "Keisha", "Kendall", "Khloe", "Kimber", "Kira", "Kiralina", "Kiraline", "Kirana",
  "Kisa", "Klara", "Klaza", "Kory", "Kresta", "Kyra",
  "Laffara", "Laksme", "Lallani", "Lara", "Lavendae", "Lavinda", "Lavinia", "Layla", "Lazora", "Ledede", "Leena",
  "Leila", "Lelani", "Lezlie", "Lilou", "Linda", "Linnia", "Lisander", "Litref", "Livindae", "Livinia", "Liza",
  "Lizandre", "Lizbethe", "Lizz", "Lucienne", "Lucy", "Lyndalla", "Lyra", "Lyza",
  "Mabel", "Madrona", "Maesie", "Malia", "Malie", "Malona", "Mandarie", "Mandy", "Manira", "Maria", "Marie",
  "Marie", "Marria", "Marrisa", "Maven", "May", "Mayown", "Meena", "Meera", "Melani", "Merisa", "Merisiel",
  "Michaela", "Michelle", "Mika", "Mikaela", "Mina", "Mindar", "Mona", "Mulana",
  "Nadine", "Nazira", "Nelani", "Noko", "Nadine", "Natalia", "Nathalza", "Nathazia", "Nan", "Neeza", "Nezra",
  "Neseen", "Niwa", "Nuzana", "Nanline", "Nan", "Noreen", "Nelia", "Namora",
  "Odariel", "Odarra", "Odelie", "Okenda", "Oki", "Olive", "Olivia", "Olla", "Ollie", "Ollienda", "Ona", "Ondexa",
  "Orchini", "Orda", "Orisan", "Oveera", "Ovendra", "Owenna", "Owennda",
  "Paige", "Paloma", "Pamola", "Payton", "Pazola", "Pelenzada", "Pell", "Pelona", "Pen", "Penella", "Penelope",
  "Pennifar", "Penny", "Peonine", "Perisel", "Perrianne", "Perriwin", "Philamena", "Phillipa", "Phlycia",
  "Phoebe", "Piper", "Polianna", "Polly", "Poppy", "Porshea", "Premila", "Prim", "Primrose", "Prudence",
  "Qadesh", "Qadesha", "Qiana", "Quandi", "Quartilla", "Queenbeyan", "Quenby", "Quenna", "Quentella", "Queshia",
  "Queta",
  "Rachela", "Rachette", "Radlyn", "Rae", "Raevan", "Raffar", "Raffaria", "Rain", "Raina", "Ramona", "Ranee",
  "Ranilda", "Rannah", "Raphalera", "Raquela", "Rashalle", "Rasheda", "Rashial", "Rashina", "Rashina", "Rashina",
  "Raven", "Ravennia", "Raxi", "Rayn", "Rayna", "Raynalda", "Reagan", "Reana", "Reanda", "Reaney", "Rebekka", "Reem",
  "Reena", "Reeva", "Reeza", "Reita", "Rella", "Renata", "Reshiel", "Rexalia", "Rexanna", "Rey", "Reychele", "Reza",
  "Rhemi", "Rhodah", "Rhonwen", "Rhyan", "Riana", "Riannah", "Rida", "Rigga", "Rikael", "Riley", "Rimenia", "Rinah",
  "Rindari", "Rindarrian", "Rindrel", "Rio", "Rissa", "Rochelle", "Roisa", "Rondell", "Roquel", "Rosanna", "Rose",
  "Rose", "Rosemarie", "Rosemary", "Rosie", "Rowena", "Rowina", "Roxanne", "Roxi", "Ruburra", "Ruby", "Rusanti",
  "Ruta", "Rutha", "Ruza", "Ryo", "Ryta",
  "Sabara", "Sabina", "Sabiya", "Sabra", "Sadhana", "Sadzee", "Saffron", "Safia", "Safia", "Safira", "Sakira",
  "Sakiri", "Sakma", "Sakme", "Salianna", "Salima", "Sallaya", "Sally", "Salma", "Samirika", "Sandaira", "Sandira",
  "Sandra", "Sandy", "Sanera", "Sanisiel", "Sannsa", "Sansa", "Satchee", "Savenna", "Sazuki", "Selani", "Selena",
  "Selene", "Selia", "Senae", "Senaye", "Senrae", "Sese", "Sesna", "Shae", "Shaelene", "Shansa", "Shantele", "Sharonne",
  "Shasta", "Shay", "Sheila", "Shilo", "Shira", "Shireena", "Shirleah", "Shirna", "Shonia", "Sia", "Siale", "Sianah",
  "Sidni", "Simina", "Sirda", "Skilar", "Skiri", "Skmee", "Skri", "Sky", "Skye", "Skylah", "Sloan", "Smalia", "Socora",
  "Sofia", "Sofie", "Solange", "Solene", "Sonia", "Sonja", "Sonyah", "Sonza", "Sookti", "Sradlei", "Starlena",
  "Stasia", "Staziar", "Suhanne", "Surinna", "Surna", "Suzzanna", "Syal", "Sylen", "Sylena", "Syona", "Syviah",
  "Tabita", "Talika", "Tamara", "Tamma", "Tavenna", "Tavna", "Tazara", "Telijah", "Terien", "Terra", "Terr'vin",
  "Tevnelle", "Tibaras", "Tika", "Torra", "Tristiel",
  "Uli", "Ulietta", "Uliette", "Ullena", "Uni", "Urannda", "Urra", "Ursa", "Ursula", "Ursun",
  "Valerize", "Valie", "Valiza", "Valori", "Vanessa", "Vania", "Vania", "Vejede", "Venalia", "Venda", "Venia",
  "Vera", "Vespa", "Vesper", "Viola", "Violet", "Violetta", "Viri", "Viv", "Vivianne", "Vivienna", "Vorun",
  "Warra", "Wendy", "Weslee", "Wigga", "Willa", "Willamena", "Willamenia", "Winifred", "Winnie", "Wren",
  "Xelli", "Xeara", "Xessa",
  "Yadesha", "Yanda", "Yarda", "Yarra", "Yarvin", "Yarvinna", "Yasmin", "Yazza", "Yenila", "Yenna", "Yesme", "Yialla",
  "Yianna", "Yibba", "Yolanda", "Yorra", "Yorrah",
  "Zaan", "Zadie", "Zakee", "Zakira", "Zala", "Zalamah", "Zalee", "Zaloma", "Zanallia", "Zania", "Zanira",
  "Zantariel", "Zantoria", "Zaphira", "Zara", "Zara", "Zarika", "Zaslan", "ZaZa", "Zeila", "Zella", "Zelli",
  "Zenda", "Zendi", "Zenella", "Zenna", "Zera", "Zezbeth", "Zilana", "Zilar", "Zilara", "Zo", "Zoe", "Zulimah",
  "Zwenia",
}

local family = {
  "Acelen", "Achilles", "Ackre", "Adstone", "Adzuts", "Anderson", "Anderson", "Anzonirus", "Anzstone", "Arcfall",
  "Archibald", "Archson", "Arcstone", "Arcstone", "Arctree", "Arcus", "Ardwick", "Arnolls", "Arrowroot", "Astersan",
  "Avoden", "Avodil", "Avodon", "Avvin", "Axblood", "Axley", "Azile",
  "Bailen", "Bailor", "Bainbridge", "Baldurksin", "Baldurson", "Barrelson", "Barretson", "Barrett", "Benson",
  "Benzen", "Bergervin", "Bertram", "Bertramus", "Berwyk", "Bickford", "Bihjan", "Bilyan", "Blackburn", "Blackleah",
  "Bladeson", "Blaggost", "Blandford", "Blandwick", "Blankley", "Bluefen", "Bluehawk", "Bluehollow", "Blundill",
  "Bolt", "Bonehand", "Boynton", "Boyton", "Branderpeak", "Branders", "Brickback", "Bundrock", "Burton",
  "Cadland", "Calamie", "Calamir", "Caldera", "Cardful", "Cardip", "Carlisle", "Carrien", "Carven", "Carver",
  "Carville", "Cavehawk", "Cherryhill", "Cornhill", "Coswald", "Cotton", "Crasswick", "Crosshill", "Crosswick",
  "Crowclaw", "Crowhammer", "Crowspirit",
  "Damenti", "Darkwood", "Dawncraw", "Deckson", "Defebo", "Deffin", "Deffindar", "Delainey", "Derru", "Derryon",
  "Deudley", "Dillan", "Dillanfar", "Dillon", "Dillson", "Dittman", "Dogtooth", "Dormir", "Dravens", "Drewhammer",
  "Drewson", "Drewstone", "Dubhorn", "Dumaron", "Dunhem", "Dunlop", "Dunmore", "Durham", "Durmarian",
  "Durnham", "Duvall",
  "Easen", "Easewild", "Eastwood", "Ebbeson", "Ebson", "Ernhaven", "Ernhelm", "Espino", "Etson", "Evarius", "Eveborn",
  "Evenglade", "Evenwood", "Everstone", "Evertt", "Everwin", "Evinland", "Evintus", "Evoden", "Evvetson", "Evvetyor",
  "Exley",
  "Fairbanks", "Fairbeak", "Fairhaven", "Fairwin", "Falkenwood", "Falkon", "Fallhammer", "Fanders", "Fanderwekken",
  "Farpeak", "Farven", "Feawell", "Febo", "Fellowton", "Fenderer", "Fesland", "Fezzel", "Fillion", "Firehelm",
  "Firken", "Flanders", "Follock", "Forstrong", "Frankhelm", "Frung",
  "Garbin", "Garvin", "Gellin", "Gellinger", "Gennik", "Gilmord", "Gilwood", "Gold", "Goldblade", "Goldcatcher",
  "Goldur", "Gorefuss", "Graftwick", "Gramalking", "Grammercy", "Grammerhelm", "Grammerstein", "Grayback", "Grayhelm",
  "Grayson", "Grayspur", "Greenerly", "Greenhill", "Greenwood", "Greffin", "Grenik", "Gresland", "Grespire",
  "Grespirt", "Greyfist", "Greylocke", "Greymalkin", "Greystone", "Greytusk", "Griffinly", "Griffiths", "Grifgard",
  "Grimm", "Grimshank", "Grimshaw", "Grizwald", "Grizwyld", "Grogoire", "Guildford", "Guilford", "Gunther",
  "Hammerborn", "Handberry", "Handstone", "Harmen", "Harmon", "Hartswold", "Hartwood", "Hartwygg", "Harvester",
  "Harvetter", "Haskins", "Haven", "Havlin", "Hawk", "Hawkeye", "Hawkins", "Hawkthorn", "Hawthorne", "Hebbson",
  "Hilder", "Hilderven", "Hill", "Hoffback", "Holly", "Hooper", "Hopper", "Hormer", "Hornclaw", "Hotspur",
  "Huntspire",
  "Icefern", "Icelock", "Iffen", "Illington", "Ireberry", "Ironfeld", "Issel", "Isslington", "Iteblade", "Ittman",
  "Ivenson", "Iverland", "Ivers", "Iverson", "Izappa", "Izzarn",
  "Jakdor", "Jakson", "Jarson", "Jatsen", "Jatten", "Jemmon", "Jenzi", "Jet", "Jetblade", "Jetlock", "Jette",
  "Jettsen", "Jiani", "Jilders", "Jittman", "Jonson", "Joren", "Jorenfen", "Jorfin", "Jorgin", "Jurnin",
  "Kagroot", "Kander", "Kanderwek", "Kannock", "Kaproot", "Karkonnen", "Kavinn", "Keeven", "Kellinger", "Kellington",
  "Kenhelm", "Kezough", "Killbar", "Killven", "Kingbeak", "Kingshammer", "Kingsmith", "Kingson", "Kingwalker",
  "Kinvek", "Kitblade", "Kitstone", "Kitt", "Koberind", "Kormand", "Kraken", "Krakenstone", "Krannock", "Kransen",
  "Kranson",
  "Lakespear", "Larson", "Larvenin", "Larville", "Lavodil", "Lavolen", "Lawfin", "Leeveen", "Lensington", "Lenzi",
  "Lexington", "Lightfoot", "Lighthammer", "Linder", "Linderen", "Litblade", "Litwick", "Lockhammer", "Lofflock",
  "Longblade", "Longblase", "Longfellow", "Lorrit", "Lovelace", "Lovelane",
  "Madwood", "Maglian", "Malvar", "Mangione", "Mappin", "Martin", "Mason", "Maximoff", "Medwood", "Midders",
  "Midstell", "Mooncatcher", "Moondarian", "Moonfel", "Moonhammer", "Moonjammer", "Moontail", "Moonwick", "Moorcok",
  "Moowik",
  "Nammon", "Nantos", "Navetusk", "Navin", "Neland", "Neldor", "Nellinger", "Nellison", "Nelven", "Nemo", "Nenwick",
  "Nero", "Nesland", "Neslann", "Nevertide", "Newland", "Neylan", "Nightcatcher", "Nighthawk", "Nightlock", "Nimmons",
  "Nimrock", "Nitslock", "Nittman", "Noonan", "Noonstone", "Norwalker", "Norwind", "Nummenhof",
  "Oakfell", "Oakson", "Oakstone", "Oaktooth", "Oberin", "Oberindos", "Oberon", "Oddson", "Offenbach", "Offentar",
  "Oldantus", "Oldback", "Oldfork", "Ollag", "Olstag", "Oltrex", "Ommenoff", "Ommenog", "Ooken", "Oorshield",
  "Oorstone", "Orcher", "Orex", "Orion", "Orrion", "Orrisend", "Oskenstone", "Osspinen", "Oswald", "Overon",
  "Oxley", "Ozfin",
  "Page", "Pagus", "Paleros", "Palevin", "Palvirus", "Palvor", "Parinos", "Passerfell", "Pasteron", "Patersol",
  "Patterfel", "Pattin", "Paudet", "Paven", "Pavingen", "Paxer", "Paxsen", "Paxton", "Paxxel", "Peele", "Peeler",
  "Pelinos", "Pelligrin", "Polyson", "Poorlock", "Prestinan",
  "Quentus", "Quickbow", "Quickrun", "Quicksilver", "Quill", "Quinton", "Quixalion",
  "Raketun", "Raksalion", "Rarkstone", "Rarkus", "Ravenswood", "Redbear", "Redding", "Redfeather", "Redfern",
  "Redhawk", "Redswallow", "Redtail", "Redwood", "Refen", "Reigus", "Revel", "Rexfort", "Reydar", "Reyson", "Riegal",
  "Rievus", "Rigby", "Rivodil", "Roberts", "Rockbear", "Rockberry", "Rockfield", "Rockpage", "Rockson", "Romenoff",
  "Roseberry", "Rosedaughter", "Rosefeld", "Rosen", "Rosenfield", "Roslin",
  "Samson", "Sandar", "Savaan", "Savalh", "Saventti", "Shunpike", "Singer", "Singers", "Skyfell", "Skyson", "Smaliel",
  "Smith", "Smithe", "Smithlin", "Smithson", "Smyth", "Songbell", "Songwick", "Sorre", "Sparks", "Sparkstone",
  "Sparkton", "Sparrow", "Spice", "Spicer", "Spinndo", "Springhawk", "Staker", "Stapleton", "Stapple", "Starblade",
  "Starfaller", "Starfend", "Stark", "Starkin", "Starklin", "Starshield", "Starwood", "Stillben", "Stillhawk",
  "Sting", "Stormwend", "Stormwood", "Strawback", "Strongbell", "Stunpike", "Sunbear", "Sunwalker",
  "Tanksun", "Taproot", "Tarven", "Teafern", "Tellven", "Tengen", "Tenhelm", "Terryberry", "Tilder", "Tillerson",
  "Tillsen", "Tillsun", "Timber", "Timberhawk", "Timberson", "Tivan", "Tompsell", "Tompsen", "Tonen", "Torre",
  "Townsend", "Townsing", "Townwin", "Townwood", "Towrend", "Traverson", "Treatenburg", "Treebar", "Treehammer",
  "Tullen", "Tung", "Turman", "Turnham", "Turnhelm", "Twinfeather", "Twinpeak", "Twinson", "Twisp", "Twist",
  "Ufflock", "Ullam", "Ullman", "Underhill", "Undertow", "Unhilder", "Urville", "Urvington", "Urvinne", "Urvintus",
  "Uskhar", "Uttman", "Uxley",
  "Vademir", "Vaingold", "Valagrin", "Valaniis", "Valltorm", "Van Gilder", "Van Wilder", "Vanonus", "Vantis",
  "Varogin", "Varvin", "Vientue", "Vientus", "Villingtar",
  "Wallburg", "Wallmen", "Walloman", "Wander", "Wanderwekken", "Warren", "Warrenson", "Warrenton", "Warron",
  "Waxley", "Wefebo", "Weffin", "Wekshield", "Wellburn", "Wellbury", "Wellings", "Wellington", "Wellman", "Wellmoon",
  "Wellsdaughter", "Wellsley", "Wellwood", "Wenaste", "Wenhawk", "Werman", "Whiteblade", "Whitefern", "Whitefoot",
  "Whitespring", "Wilaon", "Wilder", "Wilfall", "Willdersun", "Willoby", "Willowhawk", "Willows", "Willven",
  "Willvern", "Willvern", "Wiltfoot", "Wiltston", "Witberry", "Witblade", "Witbury", "Witlock", "Witrock",
  "Witsdaughter", "Woodfen", "Woodfern", "Woodfin", "Woodwick",
  "Xellenfort", "Xi", "Xillen",
  "Yarson", "Yarvin", "Yarvinin", "Years", "Yellowbeak", "Yellowhawk", "Yellstar", "Yellvin",
  "Zaffir", "Zappata", "Zexfort", "Zi", "Zweitbar", "Zwermann", "Zwi", "Zwiblade", "Zwiman",
}


return {
  male = male,
  female = female,
  family = family
}